### ISSUE TITLE
Add testing using nf-test

### ISSUE THREAD

**Issue by FloWuenne** [nf-core/molkart#12]
### Description of feature

Implement pipeline tests using the new [nf-test plugin](https://code.askimed.com/nf-test/).

**Comment by kbestak** [comment]
Important features to test:
* Full pipeline run with Cellpose and Mesmer (clahe included) - single channel
* Full pipeline run with all Cellpose and Mesmer (clahe included) - two images
* ilastik with single-channel image - already an nf-core module so this should be working
* create training crops (just 1 ROI)
* Test custom model for Cellpose option?

**Comment by FloWuenne** [comment]
Everything expect for full-test will be implemented with #25 !

**Comment by kbestak** [comment]
Full test added with https://github.com/nf-core/molkart/pull/39
Let's check the config files (saw a couple of TODOs) and then we can close this issue.
