### ISSUE TITLE
Deepcell_mesmer doesn't work on AWS with WAVE and FUSION

### ISSUE THREAD

**Issue by FloWuenne** [nf-core/molkart#56]
### Description of the bug

The current container used for Deepcell_Mesmer fails on AWS with FUSION and WAVE used for AWSmegatests. This can be fixed by making a custom Mesmer container without an entrypoint.

### Command used and terminal output

```console
Error executing process > 'NFCORE_MOLKART:MOLKART:DEEPCELL_MESMER (mem_only)'

Caused by:
  Essential container in task exited

Command executed:

  python /usr/src/app/run_app.py mesmer \
      --squeeze \
      --nuclear-image mem_only_nuclear_gridfilled_clahe.tiff \
      --output-directory . \
      --output-name mem_only_mesmer_mask.tif \
      --membrane-image mem_only_membrane_gridfilled_clahe.tiff \
      --compartment whole-cell --image-mpp 0.138 --nuclear-channel 0
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MOLKART:MOLKART:DEEPCELL_MESMER":
      deepcell_mesmer: 0.4.1
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  python: can't open file 'bash': [Errno 2] No such file or directory
  9:43AM INF shutdown filesystem start
  9:43AM INF shutdown filesystem done

Work dir:
  s3://nf-core-awsmegatests/work/molkart/work-7605a53092930a0b65509c64f79834a6c8449e9b/55/ca70aa329b1c92d09ddb282f761d60

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### System information

<img width="364" alt="grafik" src="https://github.com/nf-core/molkart/assets/11639154/8a70cdd2-aa27-4ce2-80e0-4f321c9680b8">

**Comment by kbestak** [comment]
TODO: remove mesmer from full_test config

**Comment by FloWuenne** [comment]
We can remove it, or replace the container with a custom one that removes the `ENTRYPOINT`!

**Comment by FloWuenne** [comment]
This issue should be fixed with https://github.com/nf-core/modules/pull/5195!

**Comment by FloWuenne** [comment]
@kbestak We still need to update the module in [nf-core/molkart](https://github.com/nf-core/molkart) though. Ran into this error again today while running the small test on AWS + FUSION!
