### ISSUE TITLE
Add option to filter masks and exclude mean intensities

### ISSUE THREAD

**Issue by kbestak** [nf-core/molkart#8]
### Description of feature

 Add option to filter masks and exclude mean intensities

**Comment by kbestak** [comment]
New version of the Cellpose module will have this functionality (with the min_size parameter) - param will be added once working.

spot2cell is replacing project spots and mcquant and does not produce the mean intensity metrics that should have otherwise been removed.

**Comment by FloWuenne** [comment]
https://github.com/nf-core/modules/pull/3975 is implementing the new cellpose container version. So once this passes, the filtering option can be added to cellpose via ext.args!

**Comment by kbestak** [comment]
We don't have a way of filtering ilastik and Mesmer masks yet, only Cellpose has an internal function to filter masks.

**Comment by FloWuenne** [comment]
@kbestak Should we therefore come back to our idea of filtering cells with a module after the segmentation step? This would also help to exclude weird shapes / small or big cells for visualization of the mask.

**Comment by kbestak** [comment]
@FloWuenne The question just remains, do we filter the segmentation masks themselves, or cells in the quantification table. The latter would definitely produce less data as the segmentation masks can be relatively big, and give more freedom to users, but that would make it harder for visualization as the segmentation mask would not match the quantified output. I'm leaning towards segmentation mask filtering, what do you think?

**Comment by FloWuenne** [comment]
I would agree, that segmentation mask filtering would be more helpful due to multiple reasons:
- Users can plot / visualize the actual cells they quantify
- Reduce potential file size of masks
- Maintain constant cell IDs between mask and quantification table

**Comment by kbestak** [comment]
Addressed in: https://github.com/nf-core/molkart/pull/33
