### ISSUE TITLE
Add QC parsing with MultiQC

### ISSUE THREAD

**Issue by kbestak** [nf-core/molkart#9]
### Description of feature

 Add QC parsing with MultiQC using the molcart QC output. Ideally, would also include the overview png if the create training set option is used.

**Comment by kbestak** [comment]
https://github.com/nf-core/molkart/pull/10 implements this - more QC metrics could still be added (missing Duplicated spot counts and percentage)

**Comment by FloWuenne** [comment]
Implemented by #10
